### ISSUE TITLE
提一点关于简历的意见

### ISSUE THREAD

**Issue by xiantang** [BROWN3QQQ/Resume#1]
1. 如果你的github不是非常活跃，不建议贴
2. 其实个人技能这一栏没啥用
3. 项目最好出现一些关于中间件的东西类似消息队列 
4. 半成品的东西不要贴
5. 简历的内容足够写成一页，你这样hr可能会认为你简历不够认真

**Comment by BROWN3QQQ** [comment]
谢谢你的建议，我会重新修改的简历，已经follow你的github，谢谢你
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiantang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 下午5:38
收件人:&nbsp;"BROWN3QQQ/Resume"<Resume@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[BROWN3QQQ/Resume] 提一点关于简历的意见 (#1)



 
如果你的github不是非常活跃，不建议贴
 
其实个人技能这一栏没啥用
 
项目最好出现一些关于中间件的东西类似消息队列
 
半成品的东西不要贴
 
简历的内容足够写成一页，你这样hr可能会认为你简历不够认真
